# Generated by Django 4.2 on 2025-05-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_deleted',
            new_name='is_delete',
        ),
    ]
