services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ndangdigarap
      POSTGRES_PASSWORD: ndangdigarap
      POSTGRES_DB: ndangdigarap
    ports:
      - 5440:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5010:8080

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guests
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata: