export const strings = {
    id: {
        search_placeholder: 'Cari catatan...',
        online: 'Aktif',
        dark_toggle: 'Gelap',
        light_toggle: 'Terang',
        create_note_button: 'Tambah Catatan',
        active: 'Aktif',
        archive: 'Arsip',
        not_found_archive_notes: 'Tidak ada catatan yang diarsipkan',
        archive_notes_descriptions: 'Catatan yang diarsipkan akan muncul di sini',
        not_found_active_notes: 'Belum ada catatan',
        active_notes_descriptions: 'Mulai dengan membuat catatan pertama Anda',
        detail_dropdown_button: 'Lihat detail',
        archive_dropdown_button: 'Arsipkan',
        delete_dropdown_button: 'Hapus',
        cancel_dropdown_button: 'Batalkan arsip',
        created_at: 'Dibuat pada',
        note_information: 'Informasi Catatan',
        archived: 'Diarsipkan',
        note_owner: 'Pemilik',
        date_created: 'Tanggal Dibuat',
        back_to_notes: 'Kembali ke Daftar Catatan',
        note_not_found_title: 'Catatan tidak ditemukan',
        note_not_found_description: 'Catatan yang Anda cari tidak ada atau telah dihapus.',
        delete_note_title: 'Hapus Catatan',
        delete_note_description: 'Apakah Anda yakin ingin menghapus catatan ini? Tindakan ini tidak dapat dibatalkan.',
        cancel: 'Batal',
        delete: 'Hapus',
        unarchive: 'Batalkan Arsip',
        archive_action: 'Arsipkan',
        delete_action: 'Hapus',
        loading: 'Memuat...',
        failed_to_load: 'Gagal memuat catatan',
        failed_to_delete: 'Gagal menghapus catatan',
        failed_to_archive: 'Gagal mengarsipkan catatan',
        failed_to_unarchive: 'Gagal membatalkan arsip catatan',
        unexpected_error: 'Terjadi kesalahan tak terduga',
        new_note_title: 'Catatan Baru',
        new_note_description: 'Buat catatan baru dengan judul dan isi yang menarik',
        form_title_label: 'Judul Catatan',
        form_title_placeholder: 'Masukkan judul catatan...',
        form_body_label: 'Isi Catatan',
        form_body_placeholder: 'Tulis isi catatan di sini...',
        character_count: 'karakter',
        cancel_button: 'Batal',
        save_button: 'Simpan Catatan',
        saving_button: 'Menyimpan...',
        preview_title: 'Preview',
        preview_description: 'Pratinjau catatan yang akan dibuat',
        preview_default_title: 'Judul catatan akan muncul di sini',
        preview_default_body: 'Isi catatan akan muncul di sini...',
        success_create_note: 'Catatan berhasil dibuat!',
        failed_create_note: 'Gagal membuat catatan. Silakan coba lagi.',
        error_create_note: 'Terjadi kesalahan. Silakan coba lagi.',
        login_title: 'Login',
        login_description: 'Masukkan email dan password untuk masuk',
        login_email_label: 'Email',
        login_email_placeholder: 'nama@example.com',
        login_password_label: 'Password',
        login_password_placeholder: 'Masukkan password',
        login_error_invalid: 'Email atau password salah.',
        login_error_general: 'Terjadi kesalahan. Silakan coba lagi.',
        login_button: 'Login',
        logging_in_button: 'Sedang login...',
        register_title: 'Register',
        register_description: 'Buat akun baru untuk mulai menggunakan aplikasi',
        register_name_label: 'Nama',
        register_name_placeholder: 'Masukkan nama lengkap',
        register_email_label: 'Email',
        register_email_placeholder: 'nama@example.com',
        register_password_label: 'Password',
        register_password_placeholder: 'Masukkan password',
        register_confirm_password_label: 'Konfirmasi Password',
        register_confirm_password_placeholder: 'Ulangi password',
        register_button: 'Register',
        registering_button: 'Sedang mendaftar...',
        dont_have_account: 'Tidak Punya akun?'
    },
    en: {
        search_placeholder: 'Search notes...',
        online: 'Online',
        dark_toggle: 'Dark',
        light_toggle: 'Light',
        create_note_button: 'Add Note',
        active: 'Active',
        archive: 'Archive',
        not_found_archive_notes: 'No archived notes',
        archive_notes_descriptions: 'Archived notes will appear here',
        not_found_active_notes: 'No notes yet',
        active_notes_descriptions: 'Start by creating your first note',
        detail_dropdown_button: 'View details',
        archive_dropdown_button: 'Archive',
        delete_dropdown_button: 'Delete',
        cancel_dropdown_button: 'Unarchive',
        created_at: 'Created at',
        note_information: 'Note Information',
        archived: 'Archived',
        note_owner: 'Owner',
        date_created: 'Date Created',
        back_to_notes: 'Back to Notes List',
        note_not_found_title: 'Note not found',
        note_not_found_description: 'The note you are looking for does not exist or has been deleted.',
        delete_note_title: 'Delete Note',
        delete_note_description: 'Are you sure you want to delete this note? This action cannot be undone.',
        cancel: 'Cancel',
        delete: 'Delete',
        unarchive: 'Unarchive',
        archive_action: 'Archive',
        delete_action: 'Delete',
        loading: 'Loading...',
        failed_to_load: 'Failed to load note',
        failed_to_delete: 'Failed to delete note',
        failed_to_archive: 'Failed to archive note',
        failed_to_unarchive: 'Failed to unarchive note',
        unexpected_error: 'An unexpected error occurred',
        new_note_title: 'New Note',
        new_note_description: 'Create a new note with an interesting title and content',
        form_title_label: 'Note Title',
        form_title_placeholder: 'Enter note title...',
        form_body_label: 'Note Body',
        form_body_placeholder: 'Write your note here...',
        character_count: 'characters',
        cancel_button: 'Cancel',
        save_button: 'Save Note',
        saving_button: 'Saving...',
        preview_title: 'Preview',
        preview_description: 'Preview of the note to be created',
        preview_default_title: 'Note title will appear here',
        preview_default_body: 'Note body will appear here...',
        success_create_note: 'Note successfully created!',
        failed_create_note: 'Failed to create note. Please try again.',
        error_create_note: 'An error occurred. Please try again.',
        login_title: 'Login',
        login_description: 'Enter your email and password to log in',
        login_email_label: 'Email',
        login_email_placeholder: 'name@example.com',
        login_password_label: 'Password',
        login_password_placeholder: 'Enter your password',
        login_error_invalid: 'Invalid email or password.',
        login_error_general: 'An error occurred. Please try again.',
        login_button: 'Login',
        logging_in_button: 'Logging in...',
        register_title: 'Register',
        register_description: 'Create a new account to start using the app',
        register_name_label: 'Name',
        register_name_placeholder: 'Enter your full name',
        register_email_label: 'Email',
        register_email_placeholder: 'name@example.com',
        register_password_label: 'Password',
        register_password_placeholder: 'Enter your password',
        register_confirm_password_label: 'Confirm Password',
        register_confirm_password_placeholder: 'Repeat your password',
        register_button: 'Register',
        registering_button: 'Registering...',
        dont_have_account: 'Don\'t have an account?',
    },
}
