export const strings = {
    id: {
        search_placeholder: 'Cari catatan...',
        online: 'Aktif',
        dark_toggle: 'Gelap',
        light_toggle: 'Terang',
        create_note_button: 'Tambah Catatan',
        active: 'Aktif',
        archive: 'Arsip',
        not_found_archive_notes: 'Tidak ada catatan yang diarsipkan',
        archive_notes_descriptions: 'Catatan yang diarsipkan akan muncul di sini',
        not_found_active_notes: 'Belum ada catatan',
        active_notes_descriptions: 'Mulai dengan membuat catatan pertama Anda',
        detail_dropdown_button: 'Lihat detail',
        archive_dropdown_button: 'Arsipkan',
        delete_dropdown_button: 'Hapus',
        cancel_dropdown_button: 'Batalkan arsip',
        created_at: 'Dibuat pada',
        note_information: 'Informasi Catatan',
        archived: 'Diarsipkan',
        note_owner: 'Pemilik',
        date_created: 'Tanggal Dibuat',
        back_to_notes: 'Kembali ke Daftar Catatan',
        note_not_found_title: 'Catatan tidak ditemukan',
        note_not_found_description: 'Catatan yang Anda cari tidak ada atau telah dihapus.',
        delete_note_title: 'Hapus Catatan',
        delete_note_description: 'Apakah Anda yakin ingin menghapus catatan ini? Tindakan ini tidak dapat dibatalkan.',
        cancel: 'Batal',
        delete: 'Hapus',
        unarchive: 'Batalkan Arsip',
        archive_action: 'Arsipkan',
        delete_action: 'Hapus',
        loading: 'Memuat...',
        failed_to_load: 'Gagal memuat catatan',
        failed_to_delete: 'Gagal menghapus catatan',
        failed_to_archive: 'Gagal mengarsipkan catatan',
        failed_to_unarchive: 'Gagal membatalkan arsip catatan',
        unexpected_error: 'Terjadi kesalahan tak terduga',
        new_note_title: 'Catatan Baru',
        new_note_description: 'Buat catatan baru dengan judul dan isi yang menarik',
        form_title_label: 'Judul Catatan',
        form_title_placeholder: 'Masukkan judul catatan...',
        form_body_label: 'Isi Catatan',
        form_body_placeholder: 'Tulis isi catatan di sini...',
        character_count: 'karakter',
        cancel_button: 'Batal',
        save_button: 'Simpan Catatan',
        saving_button: 'Menyimpan...',
        preview_title: 'Preview',
        preview_description: 'Pratinjau catatan yang akan dibuat',
        preview_default_title: 'Judul catatan akan muncul di sini',
        preview_default_body: 'Isi catatan akan muncul di sini...',
        success_create_note: 'Catatan berhasil dibuat!',
        failed_create_note: 'Gagal membuat catatan. Silakan coba lagi.',
        error_create_note: 'Terjadi kesalahan. Silakan coba lagi.',
        login_title: 'Login',
        login_description: 'Masukkan email dan password untuk masuk',
        login_email_label: 'Email',
        login_email_placeholder: 'nama@example.com',
        login_password_label: 'Password',
        login_password_placeholder: 'Masukkan password',
        login_error_invalid: 'Email atau password salah.',
        login_error_general: 'Terjadi kesalahan. Silakan coba lagi.',
        login_button: 'Login',
        logging_in_button: 'Sedang login...',
        register_title: 'Register',
        register_description: 'Buat akun baru untuk mulai menggunakan aplikasi',
        register_name_label: 'Nama',
        register_name_placeholder: 'Masukkan nama lengkap',
        register_email_label: 'Email',
        register_email_placeholder: 'nama@example.com',
        register_password_label: 'Password',
        register_password_placeholder: 'Masukkan password',
        register_confirm_password_label: 'Konfirmasi Password',
        register_confirm_password_placeholder: 'Ulangi password',
        register_button: 'Register',
        registering_button: 'Sedang mendaftar...',

    },
    en: {
        search_placeholder: 'Search notes...',
    },
};
